[tool.poetry]
name = "my-python-package"
version = "0.1.0"
description = ""
authors = ["Suwon Park <sepiabrown@naver.com>"]

[tool.poetry.dependencies]
python = "~3.9"
pyro-ppl = "^1.8.0"
torch = {version = "1.11.0+cu115", source = "torchWithCuda"}
torchvision = "^0.12.0" # needs explicit : scipy
scipy = "<1.8.0" #"^1.8.0"
pandas = "1.4.2"
kiwisolver = "<=1.3.2"
cppy = "<=1.1.0"
tomli = "<=1.2.3"
keras = "^2.8.0"
numpy = "1.21.5"
matplotlib = "^3.5.1"
tensorflow = "^2.8.0"
#pymc3 = "^3.11.4"
seaborn = "^0.11.2"
#Theano = "1.0.5"
#aesara = "2.5.3"
#pycuda = "^2021.1"
pymc-nightly = "4.0.0-beta.2-dev.20220304"
jaxlib = "^0.3.10"
#jaxlib = { path = "jaxlib-0.1.65+cuda112-cp39-none-manylinux2010_x86_64.whl" }
jax = "^0.3.13"
numpyro = "^0.9.2"

# Needed for polynote
#numpy
#pandas==1.2.5
virtualenv = "*"
ipython = "*"
nbconvert = "*"
jedi = ">=0.18.1"
jep = "4.0.0"

#[[tool.poetry.source]]
#name = "jaxlibWithCuda"
##url = "https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.3.8+cuda11.cudnn82-cp39-none-manylinux2014_x86_64.whl"
#url = "https://storage.googleapis.com/jax-releases/cuda11"
#secondary = true

[[tool.poetry.source]]
name = "torchWithCuda"
# ex) url = "https://download.pytorch.org/whl/cu115/torch-1.11.0%2Bcu115-cp39-cp39-linux_x86_64.whl"
url = "https://download.pytorch.org/whl/cu115"
# Solution: secondary = true, default with no option 
secondary = true

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
